### PR TITLE
make `Makefile` a bit more packaging friendly

### PR DESCRIPTION
**Pull request by rindeal**
Also please tag a release, so that I don't have to reference the snapshots by commit hashes.

### CODE REVIEW

**Comment by adsr** [comment]
Thanks for the PR. I'm OK to merge most of this but would like to avoid using `pkg-config`. Except for the hard-coded `-lpcre` part, is there something about the current env var approach that makes this difficult to package?

**Comment by rindeal** [comment]
I'm not sure I understood you correctly. So you want me to keep just the `$(shell pkg-config libpcre --libs-only-l)` line? And what do you mean by "the current env var approach"?

**Comment by adsr** [comment]
By current env var approach I meant this pattern:

    mlbuf_cflags:=$(CFLAGS) -D_GNU_SOURCE -Wall -g -fPIC

etc, which allows you to pass in additional `CFLAGS` by env var. For example if you want to pass in additional flags from `pkg-config`, you can do this:

    $ CFLAGS=$(shell pkg-config libpcre --cflags) make

instead of invoking `pkg-config` in the Makefile itself.

The one place where this doesn't work is `-lpcre` which is currently hard-coded. However we can add another var to override it.

This way there is no explicit dependency on `pkg-config`. What do you think?

**Comment by rindeal** [comment]
The ability to pass values through env vars is preserved thanks to the `?=` operator and is in fact the core idea behind this PR as package building systems need to pass their own standardized values.

pkg-config is pretty much the standard, but I don't judge. So if you want to have just optional support I'd imagine having something like this - https://github.com/rindeal/mlbuf/blob/patch-2/Makefile, which tries to emulate autoconf's behaviour.

Now to build without pkg-config:

```
$ LIBPCRE_CFLAGS= LIBPCRE_LDFLAGS= LIBPCRE_LDLIBS="-lpcre" make
```

**Comment by rindeal** [comment]
All right, I've updated the branch with the exact copy of your final proposal as it will work for me.

**Comment by adsr** [comment]
Thanks @rindeal. Merged and tagged a release as well.

**Comment by rindeal** [comment]
Yes, I have already updated my package (https://github.com/rindeal/rindeal-ebuild-repo/tree/master/sys-libs/mlbuf). Thank you as well.

**Pull request merged**
